# Generated by Django 5.2.5 on 2025-09-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
    ]
